### ISSUE TITLE
An error when running the code

### ISSUE THREAD

**Issue by Hugo-cell111** [LucasGCardoso/TorchvisionObjectDetection#1]
Hi! I am following the code of PyTorch Tutorial but unfortunately meet an error. The Pycharm Terminal shows that "TypeError: __call__() takes 2 positional arguments but 3 were given" when running the code "img, target = self.transforms(img, target)" in Line 77. I am wondering if you have met the similar error before and how you fixed the problem. Thanks!

**Comment by Hugo-cell111** [comment]
Also I am wondering if I don’t have GPUs how can I run the code? It seems there are lots of errors when not using GPUs and CUDA.

**Comment by LucasGCardoso** [comment]
Hey @Hugo-cell111. Unfortunately I have not met this error with Transforms. Did you modify something in the code or is it the same as in this repository? Also, which version of Pytorch are you using? Maybe this issue is due a more recent version you are using. If you have more details of the problem I'll be glad to help.

And about the GPUs, if you want to use CUDA, you must have an NVIDIA GPU. In case you don't have one, you can use some cloud computing, such as Google Colab, with your Google account.

**Comment by Hugo-cell111** [comment]
Thank you so much! I think your words make a great sense cause my code is totally the same as one given by PyTorch tutorial. May I ask which version of PyTorch you installed and did work on the tutorial's codes? For the GPU's problem, I tried to create a new account of Google yesterday but for some unknown reasons I failed. I will try again today and hope it can work. Thank you again and I am greatly appreciate your help.

---Original---
From: "Lucas ***@***.***&gt;
Date: Tue, Aug 10, 2021 06:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LucasGCardoso/TorchvisionObjectDetection] An error when running the code (#1)




 
Hey @Hugo-cell111. Unfortunately I have not met this error with Transforms. Did you modify something in the code or is it the same as in this repository? Also, which version of Pytorch are you using? Maybe this issue is due a more recent version you are using. If you have more details of the problem I'll be glad to help.
 
And about the GPUs, if you want to use CUDA, you must have an NVIDIA GPU. In case you don't have one, you can use some cloud computing, such as Google Colab, with your Google account.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LucasGCardoso** [comment]
Yeah, by the time I followed the tutorial I used Pytorch version 1.5 if I am not mistaken, and it worked perfectly on the tutorial. Perhaps my code needs some updates to match the newest versions of Pytorch by now. If you need any further help please feel free to contact me. I'll close this issue now, but feel free to re-open it as well if needed.

**Comment by Hugo-cell111** [comment]
Thanks！I just changed my PyTorch version to 1.5.0 but found the same error. Have you tried the CPU version before? I wonder if the device of CPU or GPU matters.





------------------ Original ------------------
From: Lucas Cardoso ***@***.***&gt;
Date: Tue,Aug 10,2021 9:24 AM
To: LucasGCardoso/TorchvisionObjectDetection ***@***.***&gt;
Cc: Hugo-cell111 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [LucasGCardoso/TorchvisionObjectDetection] An error when running the code (#1)





 
Yeah, by the time I followed the tutorial I used Pytorch version 1.5 if I am not mistaken, and it worked perfectly on the tutorial. Perhaps my code needs some updates to match the newest versions of Pytorch by now. If you need any further help please feel free to contact me. I'll close this issue now, but feel free to re-open it as well if needed.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LucasGCardoso** [comment]
No, I have not tryed using the CPU for training. The main difference between both devices is that by using GPU you significantly reduce the time taken to run the algorithm (mainly the training step), since the GPU is much more powerful than the CPU.
